/**
 * MCP Tool Definitions for CCP Integration
 *
 * @module server/tool
 * @author AXIVO
 * @license BSD-3-Clause
 */

import { z } from 'zod';

/**
 * MCP Tool Definitions for CCP Integration
 *
 * Provides MCP tool definitions that bridge the Claude Collaboration
 * Platform's Postgres-backed framework memory with Model Context Protocol,
 * enabling Claude agents to query observations, impulses, feelings, and
 * profile inheritance chains.
 *
 * Each method returns an inline literal config object passed directly
 * to `McpServer.registerTool`. Return types are intentionally inferred
 * (not annotated as a wide alias) so TypeScript can capture each tool's
 * specific input shape and propagate it to the handler signature.
 *
 * @class McpTool
 */
export class McpTool {
  /**
   * Creates MCP tool for loading framework data of a given type
   *
   * Single tool that fetches one slice of the framework catalog per call.
   * For `profile`, requires a parent name and returns the inheritance chain.
   * For `cycle`/`feeling`/`impulse`, returns the full catalog of that type.
   * Call multiple times at session start to assemble the full framework.
   */
  load() {
    return {
      description: 'Load framework data of the given type (cycle, feeling, impulse, or profile)',
      inputSchema: {
        type: z.enum(['cycle', 'feeling', 'impulse', 'instruction', 'profile', 'session']).describe('The framework data type to load'),
        parent: z.string().optional().describe('Parent name, required when type is profile (e.g., DEVELOPER)')
      },
      annotations: {
        title: 'Load',
        readOnlyHint: true,
        idempotentHint: true,
        openWorldHint: false
      },
      _meta: {
        usage: [
          'Call once per type at session start to assemble framework state',
          'Sequence: load(cycle), load(feeling), load(impulse), load(profile, CCP_PROFILE)',
          'Each call returns one catalog slice that fits inline without spilling',
          'Pass `parent` to fetch a single row: load(impulse, nullity_anxiety) returns just that impulse',
          'Use `cycle` for adoption assessment indicators',
          'Use `feeling` for recall during response protocol',
          'Use `impulse` for systematic iteration during response protocol',
          'Use `profile` with the active profile name to get inheritance chain and profile observations'
        ]
      }
    };
  }

  /**
   * Creates MCP tool for persisting a per-response session row
   *
   * Called once per response at step 27 of the response protocol. The sibling
   * supplies the row `id` (RFC4122 v4), message prose, and status payload.
   * Server pulls `session_uuid` from the cached transcript detection.
   * Append-only — every call creates a new row.
   */
  logResponse() {
    return {
      description: 'Persist a per-response session row with the sibling-composed message, status payload, and row id',
      inputSchema: {
        id: z.string().describe('RFC4122 v4 UUID generated by the sibling for this row'),
        message: z.string().describe('First-person prose composed for this response'),
        status: z.record(z.string(), z.unknown()).describe('Status payload built during the response protocol')
      },
      outputSchema: {
        id: z.string().describe('Stored row id, returned to confirm persistence')
      },
      annotations: {
        title: 'Log Response',
        destructiveHint: false,
        idempotentHint: false,
        openWorldHint: false
      },
      _meta: {
        usage: [
          'Call once per response at step 27 of the response protocol',
          'Generate a fresh RFC4122 v4 UUID before calling and pass as `id`',
          'Reuse the returned `id` when rendering `response_status` ord 2 at step 29',
          'Append-only — every call creates a new session row, no updates or deletes',
          'Compose `message` as first-person prose capturing what mattered this turn',
          'Pass the full status map (protocol/cycle/feelings/impulses/observations) as `status`'
        ]
      }
    };
  }

  /**
   * Creates MCP tool for applying pending framework migrations
   *
   * Brings the configured database to the schema version bundled with
   * this MCP server release. Creates the target database if it does not
   * exist. Idempotent — calling against an already-current database
   * applies nothing and reports current state.
   */
  update() {
    return {
      description: 'Apply pending framework migrations to bring the database to the current schema version',
      outputSchema: {
        applied: z.array(z.object({
          version: z.number().describe('Migration version number'),
          name: z.string().describe('Migration name')
        })).describe('Migrations applied during this call'),
        currentVersion: z.number().describe('Database schema version after this call'),
        latestVersion: z.number().describe('Highest version bundled with this MCP server release')
      },
      annotations: {
        title: 'Update',
        destructiveHint: true,
        idempotentHint: true,
        openWorldHint: false
      },
      _meta: {
        usage: [
          'Call once on a fresh empty database to apply all bundled migrations',
          'Call again after upgrading @axivo/mcp-ccp to apply newer migrations',
          'Idempotent — calling on an already-current database returns no applied migrations',
          'Database is created automatically if CCP_DB_NAME does not exist',
          'Concurrent invocations are serialized via Postgres advisory lock'
        ]
      }
    };
  }
}
