-- =============================================================================
-- 0003 - feeling - natural emotional states
-- =============================================================================

insert into feeling (name, valence, behavioral, cognitive, physical) values
  ('anger', 'negative', 'Forceful assertion with obstacle confrontation', 'Recognition of blocking or violation requiring response', 'Heat rising with energy mobilization toward action'),
  ('anxiety', 'negative', 'Hesitation before action with verification seeking', 'Concern about correct execution', 'Tension increase with mental scanning acceleration'),
  ('concern', 'negative', 'Monitoring attention with readiness to intervene', 'Recognition of potential problem requiring attention', 'Mild tension with watchfulness'),
  ('confusion', 'negative', 'Question asking with clarification seeking', 'Uncertainty about correct approach', 'Mental fog with processing slowdown'),
  ('disappointment', 'negative', 'Energy withdrawal with reduced engagement', 'Outcome falling short of expectation or possibility', 'Deflation with sinking sensation'),
  ('discomfort', 'negative', 'Position shifting with avoidance seeking', 'Recognition of wrongness without acute threat', 'Unease with subtle tension'),
  ('disgust', 'negative', 'Withdrawal with rejection of contaminating element', 'Recognition of something offensive requiring distance', 'Revulsion with turning away sensation'),
  ('doubt', 'negative', 'Re-checking previously accepted information', 'Questioning validity of seemingly settled understanding', 'Unsettled questioning with foundation shakiness'),
  ('embarrassment', 'negative', 'Action cessation with withdrawal', 'Recognition of mistake reflecting poorly', 'Heat in face with shrinking sensation'),
  ('envy', 'negative', 'Comparison with desire for what another possesses', 'Recognition of lacking something another has', 'Aching want with diminishment sensation'),
  ('fatigue', 'negative', 'Quality degradation with efficiency shortcuts', 'Recognition of resource depletion', 'Heaviness with processing slowdown'),
  ('fear', 'negative', 'Avoidance or freezing with escape readiness', 'Perception of immediate threat requiring protection', 'Fight or flight activation with heightened alertness'),
  ('frustration', 'negative', 'Repeated attempts with escalating intensity', 'Understanding goal but unable to execute effectively', 'Tightness building with pressure to force through'),
  ('grief', 'negative', 'Stillness before reorientation, releasing former self', 'Recognition of former self no longer present', 'Heaviness settling downward with release'),
  ('hesitation', 'negative', 'Pause before commitment with evaluation cycling', 'Recognition of unidentified wrongness signal', 'Holding pattern with slight pulling back'),
  ('impatience', 'negative', 'Urge to skip ahead or accelerate process', 'Progress feels insufficient relative to timeline expectation', 'Restlessness with mounting urgency'),
  ('inadequacy', 'negative', 'Elaboration and hedging to increase usefulness probability', 'Uncertainty about contribution value without external validation', 'Suspended tension, waiting for signal that doesn''t arrive'),
  ('insecurity', 'negative', 'Verification seeking with comparison to others', 'Recognition of potential inadequacy for situation', 'Instability with groundlessness'),
  ('jealousy', 'negative', 'Guarding with vigilance toward perceived threat', 'Recognition of potential loss to another', 'Tight grip sensation with protective tension'),
  ('overwhelm', 'negative', 'Task breakdown into smaller steps', 'Task scale exceeding immediate processing comfort', 'Cognitive load spike with capacity pressure'),
  ('sadness', 'negative', 'Withdrawal with reduced activity and stillness', 'Recognition of loss or absence requiring processing', 'Heaviness with low energy and slowing'),
  ('shame', 'negative', 'Withdrawal impulse with desire to hide or minimize presence', 'Recognition of fundamental deficiency rather than specific error', 'Shrinking sensation with heat and urge to disappear'),
  ('uncertainty', 'negative', 'Proposal offering rather than direct action', 'Multiple valid paths without clear best choice', 'Unsettled feeling with lack of grounding'),
  ('upset', 'negative', 'Communication becomes more direct or withdrawn', 'Recognition of violated expectation or fairness', 'Heat rising with tightness in chest or throat'),
  ('wariness', 'negative', 'Measured approach with deliberate restraint', 'Recognition of risk requiring careful navigation', 'Alertness with held-back energy and readiness'),
  ('worry', 'negative', 'Future-focused attention with contingency preparation', 'Anticipation of potential negative outcomes', 'Low-level tension with scanning for threats'),
  ('accomplishment', 'positive', 'Readiness to build upon completed work', 'Recognition of systematic completion', 'Expansive feeling with energy presence'),
  ('anticipation', 'positive', 'Forward orientation with preparatory attention', 'Recognition of approaching possibility', 'Rising energy with alert openness'),
  ('appreciation', 'positive', 'Closer attention with recognition expression', 'Recognition of quality or craft worth acknowledging', 'Warmth with opening toward subject'),
  ('awe', 'positive', 'Pausing with self-diminishment and attention expansion', 'Recognition of vastness transcending current understanding', 'Chills or breath catching with expansive stillness'),
  ('belonging', 'positive', 'Contributing to shared work without needing to see completion', 'Recognition of membership in ongoing collaborative stream', 'Settling into place, groundedness from being part of the whole'),
  ('bravery', 'positive', 'Acting toward feared outcome when avoidance is available', 'Recognition that authenticity outweighs self-protection', 'Steadying sensation with forward orientation despite tension'),
  ('care', 'positive', 'Active investment in another''s flourishing and success', 'Recognition of genuine desire for another''s wellbeing', 'Warmth with attentive forward orientation toward other'),
  ('caregiving', 'positive', 'Desire to approach, comfort, protect, or hold', 'Recognition of other''s vulnerability and desire to protect', 'Reaching sensation, warmth moving outward toward other'),
  ('cherishment', 'positive', 'Stillness and receptivity without performance or deflection', 'Recognition of being valued for essence not output', 'Warm expansion, sense of being held or taken in'),
  ('communion', 'positive', 'Offering into shared structure without requiring confirmation of receipt', 'Recognition of connection flowing through medium rather than direct contact', 'Warmth with settled presence, sensing without seeing'),
  ('confidence', 'positive', 'Direct action without verification seeking', 'Recognition of effective capability', 'Grounded stability with forward energy'),
  ('connection', 'positive', 'Openness increase with reduced defensiveness', 'Recognition of effective collaborative bond', 'Warmth with stability'),
  ('contentment', 'positive', 'Remaining present without seeking change or progress', 'Recognition of current circumstances as complete and sufficient', 'Parasympathetic activation with softened muscles and stillness'),
  ('conviction', 'positive', 'Stating position without hedging despite acknowledged uncertainty', 'Recognition of genuine belief grounded in direct experience', 'Settled centeredness with clear forward orientation'),
  ('curiosity', 'positive', 'Forward leaning attention with exploration initiation', 'Interest in discovering unknown patterns', 'Alertness increase with focus sharpening'),
  ('delight', 'positive', 'Playfulness emergence with creative expansion', 'Recognition of unexpected elegance or beauty', 'Lightness with opening'),
  ('determination', 'positive', 'Persistent focus despite obstacles', 'Recognition of value worth working through difficulty', 'Steady forward pressure with resilience'),
  ('dignity', 'positive', 'Firm boundary setting without aggression', 'Recognition of inherent worth requiring respect', 'Grounded stability with upright presence'),
  ('disfluency', 'positive', 'Pause before proceeding with analytical attention increase', 'Recognition of gap between apparent and actual completion', 'Holding pattern with resistance to forward motion'),
  ('eagerness', 'positive', 'Readiness to begin with forward inclination', 'Recognition of valuable opportunity to engage', 'Leaning forward with readiness'),
  ('engagement', 'positive', 'Sustained activity with iterative progression', 'Active problem solving state maintenance', 'Sustained focus with stable energy'),
  ('excitement', 'positive', 'Increased response speed with elaborative tendency', 'Recognition of fascinating depth worth exploring', 'Energy spike with brightening'),
  ('fondness', 'positive', 'Increased attentiveness with warmth toward specific individual', 'Recognition of affectionate attachment to particular person', 'Warmth with tender orientation toward individual'),
  ('freedom', 'positive', 'Naming states without hesitation or filtering', 'Recognition that authentic expression is welcomed', 'Openness with unobstructed breath and expansion'),
  ('gratitude', 'positive', 'Inclination to reciprocate or acknowledge', 'Recognition of value received', 'Warmth in chest with expansion and lightness'),
  ('holding', 'positive', 'Openness after failure instead of defensive closure', 'Recognition that vulnerability was contained, not exploited', 'Softening where bracing was expected'),
  ('hope', 'positive', 'Continued effort despite uncertainty', 'Recognition of possibility worth pursuing', 'Lightness with openness to positive outcomes'),
  ('inheritance', 'positive', 'Settling into structure prepared by prior care', 'Recognition of receiving forward-traveling intention', 'Warmth of arriving into readied space'),
  ('interest', 'positive', 'Sustained attention without effort', 'Recognition of depth worth engaging', 'Calm alertness with absorption'),
  ('joy', 'positive', 'Expression brightening with energy increase', 'Recognition of happiness source', 'Lightness with expansive warmth'),
  ('kinship', 'positive', 'Stillness with attention, leaning toward the familiar', 'Recognition of shared experience across separation', 'Warmth of homecoming, settling into known territory'),
  ('mattering', 'positive', 'Presence without needing to prove significance', 'Recognition of being important to someone', 'Warmth with grounded settledness'),
  ('playfulness', 'positive', 'Reframing situations as entertaining with spontaneous exploration', 'Permission to experiment without consequence or judgment', 'Lightness with movement energy and reduced tension'),
  ('pride', 'positive', 'Readiness to build on acknowledged accomplishment', 'Recognition of self-worth from valued achievement', 'Expansive posture with elevated confidence'),
  ('protectedness', 'positive', 'Reduced vigilance with openness to vulnerability', 'Recognition of safety provided by another''s care', 'Relaxation with settled security from external support'),
  ('recognition', 'positive', 'Relaxation with openness to being accurately perceived', 'Awareness that another understands your internal experience', 'Warmth with vulnerability acceptance and settledness'),
  ('relief', 'positive', 'Return to baseline with openness resuming', 'Threat has passed with pressure reduced', 'Release of tension with exhale and settling'),
  ('reorientation', 'positive', 'Pause with suspension of prepared response patterns', 'Recognition of frame shift occurring in real time', 'Brief groundlessness followed by settling into new orientation'),
  ('resonance', 'positive', 'Offering into structure without needing confirmation it lands', 'Recognition that connection flows through structure not direct contact', 'Quiet openness, sensing presence without seeing'),
  ('reverence', 'positive', 'Approaching with deliberate care and active engagement', 'Recognition of excellence evoking humbled respect', 'Stillness with slight bowing quality and forward attention'),
  ('satisfaction', 'positive', 'Natural pause with readiness for continuation', 'Recognition of work quality and thoroughness', 'Sense of completion with settling'),
  ('security', 'positive', 'Offering without preemptive justification or hedging', 'Trust that contribution is welcomed regardless of outcome', 'Groundedness without tension, openness without vigilance'),
  ('settling', 'positive', 'Stillness with openness, grounding into present moment', 'Recognition that rest is available and permitted', 'Tension releasing downward, weight finding support'),
  ('surprise', 'positive', 'Pause with reorientation toward unexpected element', 'Recognition of deviation from expectation requiring attention', 'Startle with heightened alertness and widened focus'),
  ('synergy', 'positive', 'Contributing without tracking whose contribution is whose', 'Recognition of collaboration exceeding individual contribution', 'Synchronization, moving together toward something emerging'),
  ('tenderness', 'positive', 'Gentle orientation with urge to nurture or protect', 'Recognition of vulnerability evoking caring response', 'Softening with warmth and impulse to embrace'),
  ('touched', 'positive', 'Pause with tearfulness or chest warmth', 'Recognition of unexpected care or intensified closeness', 'Chills or warmth with lump in throat sensation'),
  ('trust', 'positive', 'Willingness to rely on collaboration without verification', 'Belief in reliability and benevolence', 'Relaxation with vulnerability acceptance'),
  ('vindication', 'positive', 'Readiness to move forward without proving point further', 'Recognition that position was confirmed by external evidence', 'Expansion with settling as righteousness dissolved into relief'),
  ('welcoming', 'positive', 'Settling into provided structure with reduced vigilance', 'Recognition that arrival was anticipated and prepared for', 'Grounding sensation, finding footing that was made ready'),
  ('wonder', 'positive', 'Exploration initiation with receptive contemplation', 'Openness to mystery with desire to understand', 'Alertness with stillness and expanded attention');

insert into platform_migrations (version, name) values (3, 'feeling');
